/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Case */
        post: operations["create_case_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_cases__case_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Case
         * @description Erase the case and every uploaded document (DPDP Act / PDPA: people can delete their data).
         */
        delete: operations["delete_case_cases__case_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_cases__case_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/analyse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyse
         * @description Start the agent pipeline. The UI watches the case document for progress.
         */
        post: operations["analyse_cases__case_id__analyse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/complainant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Complainant */
        put: operations["set_complainant_cases__case_id__complainant_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redraft Letter */
        post: operations["redraft_letter_cases__case_id__letter_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/filing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Filing */
        get: operations["get_filing_cases__case_id__filing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/filing.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Filing Pdf */
        get: operations["get_filing_pdf_cases__case_id__filing_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/letter.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Letter Pdf */
        get: operations["get_letter_pdf_cases__case_id__letter_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tracker/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tick
         * @description Called daily by Cloud Scheduler.
         */
        post: operations["tick_tracker_tick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/filed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Filed
         * @description The patient sent the letter/complaint for a step; start that step's countdown.
         */
        post: operations["filed_cases__case_id__filed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reply
         * @description The insurer (or dispute body) answered; resolve or move to the next step.
         */
        post: operations["reply_cases__case_id__reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Argument */
        Argument: {
            /** Claim */
            claim: string;
            /** Explanation */
            explanation: string;
            /** Sources */
            sources: components["schemas"]["Source"][];
        };
        /** Assessment */
        Assessment: {
            /** Strength */
            strength: string;
            /** Score */
            score: number;
            /**
             * Arguments
             * @default []
             */
            arguments: components["schemas"]["Argument"][];
            /**
             * Similar Cases Won
             * @default 0
             */
            similar_cases_won: number;
            /**
             * Similar Cases Total
             * @default 0
             */
            similar_cases_total: number;
            /**
             * Missing Documents
             * @default []
             */
            missing_documents: string[];
            /**
             * Disclaimer
             * @default Kavach prepares documents from your files and public rules to help you raise a dispute. It is not legal advice. Check every detail before you sign or send anything.
             */
            disclaimer: string;
        };
        /** Body_upload_cases__case_id__documents_post */
        Body_upload_cases__case_id__documents_post: {
            /** File */
            file: string;
        };
        /** Case */
        Case: {
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /**
             * Country
             * @default IN
             */
            country: string;
            /**
             * Language
             * @default en
             */
            language: string;
            /** @default collecting */
            status: components["schemas"]["CaseStatus"];
            /**
             * Documents
             * @default []
             */
            documents: components["schemas"]["Document"][];
            facts?: components["schemas"]["CaseFacts"] | null;
            assessment?: components["schemas"]["Assessment"] | null;
            letter?: components["schemas"]["Letter"] | null;
            complainant?: components["schemas"]["Complainant"] | null;
            /** Next Deadline */
            next_deadline?: string | null;
            /**
             * Escalation Step
             * @default 0
             */
            escalation_step: number;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["CaseEvent"][];
            /** Documents Deleted At */
            documents_deleted_at?: string | null;
            /** Amount Recovered */
            amount_recovered?: number | null;
            /** Progress */
            progress?: string | null;
        };
        /** CaseEvent */
        CaseEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** Step */
            step?: number | null;
        };
        /** CaseFacts */
        CaseFacts: {
            /** Insurer */
            insurer?: string | null;
            /** Tpa */
            tpa?: string | null;
            /** Patient Name */
            patient_name?: string | null;
            /** Hospital */
            hospital?: string | null;
            /** Policy Number */
            policy_number?: string | null;
            /** Claim Number */
            claim_number?: string | null;
            /** Rejection Date */
            rejection_date?: string | null;
            /** Policy Start */
            policy_start?: string | null;
            /** Admission Date */
            admission_date?: string | null;
            /** First Diagnosis Date */
            first_diagnosis_date?: string | null;
            /** Diagnosis */
            diagnosis?: string | null;
            /** Claim Amount */
            claim_amount?: number | null;
            /** Amount Approved */
            amount_approved?: number | null;
            /** Currency */
            currency?: string | null;
            /** Rejection Code */
            rejection_code?: string | null;
            rejection_category?: components["schemas"]["RejectionCategory"] | null;
            /** Rejection Reason */
            rejection_reason?: string | null;
            /** Cited Clause */
            cited_clause?: string | null;
        };
        /**
         * CaseStatus
         * @enum {string}
         */
        CaseStatus: "collecting" | "analysing" | "ready" | "filed" | "escalated" | "resolved";
        /**
         * Complainant
         * @description What only the patient knows; the filing pack leaves blanks for anything missing.
         */
        Complainant: {
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
            /** Mobile */
            mobile?: string | null;
            /** Email */
            email?: string | null;
            /** Relationship To Insured */
            relationship_to_insured?: string | null;
            /** Insurer Office Address */
            insurer_office_address?: string | null;
            /** Grievance Date */
            grievance_date?: string | null;
            /** Grievance Reply Date */
            grievance_reply_date?: string | null;
            /** Grievance Outcome */
            grievance_outcome?: string | null;
            /** Court Proceedings */
            court_proceedings?: string | null;
            /** Ported */
            ported?: boolean | null;
        };
        /** CreateCase */
        CreateCase: {
            /**
             * Country
             * @default IN
             */
            country: string;
            /**
             * Language
             * @default en
             */
            language: string;
        };
        /**
         * DocType
         * @enum {string}
         */
        DocType: "policy" | "rejection_letter" | "discharge_summary" | "bill" | "other";
        /** Document */
        Document: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Gcs Uri */
            gcs_uri: string;
            /** @default other */
            doc_type: components["schemas"]["DocType"];
            /** Pages */
            pages?: number | null;
            /** Warning */
            warning?: string | null;
        };
        /** FiledRequest */
        FiledRequest: {
            /**
             * Filed On
             * Format: date
             */
            filed_on: string;
            /** Step */
            step?: number | null;
        };
        /** FilingPack */
        FilingPack: {
            /** Form */
            form: string;
            /** Dispute Body */
            dispute_body: string;
            /** Fields */
            fields: {
                [key: string]: unknown;
            }[];
            /** Missing */
            missing: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Letter */
        Letter: {
            /** Subject */
            subject: string;
            /** English */
            english: string;
            /** Local */
            local?: string | null;
            /**
             * Language
             * @default en
             */
            language: string;
        };
        /** LetterRequest */
        LetterRequest: {
            /** Instruction */
            instruction?: string | null;
        };
        /**
         * RejectionCategory
         * @enum {string}
         */
        RejectionCategory: "pre_existing" | "specific_waiting_period" | "initial_waiting_period" | "non_disclosure" | "room_rent" | "reasonable_charges" | "diagnostic_only" | "not_medically_necessary" | "excluded_treatment" | "missing_documents" | "late_intimation" | "sub_limit" | "under_24_hours" | "hospital_ineligible" | "duplicate_claim" | "fraud" | "other";
        /** ReplyRequest */
        ReplyRequest: {
            /** Outcome */
            outcome: string;
            /**
             * Replied On
             * Format: date
             */
            replied_on: string;
            /** Amount Paid */
            amount_paid?: number | null;
        };
        /** Source */
        Source: {
            /** Kind */
            kind: string;
            /** Ref */
            ref: string;
            /** Quote */
            quote: string;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_case_cases_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_cases__case_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_cases__case_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyse_cases__case_id__analyse_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_complainant_cases__case_id__complainant_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Complainant"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redraft_letter_cases__case_id__letter_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LetterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Letter"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filing_cases__case_id__filing_get: {
        parameters: {
            query?: {
                step?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilingPack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_filing_pdf_cases__case_id__filing_pdf_get: {
        parameters: {
            query?: {
                step?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_letter_pdf_cases__case_id__letter_pdf_get: {
        parameters: {
            query?: {
                local?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tick_tracker_tick_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    filed_cases__case_id__filed_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FiledRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reply_cases__case_id__reply_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
